Switch to return symbols for `AbstractModel#show_controller`, `show_action`, `index_action`, `destroy_action`
MushroomObserver/mushroom-observer pull request #1111
Opened 2022-07-22 01:25 UTC by nimmolo

To make Joe's `HerbariaController` refactor work, he discovered that Rails assumes it needs to prepend the controller namespace to the controller action, if the caller is a namespaced controller like `Herbaria::MergesController`. However, this leads Rails to build inaccurate controller namespaces like `herbaria/herbaria`. If you send the controller name as a string prepended by a leading forward slash, though, Rails won't prepend the namespace, and you'll be back to `herbaria` as desired.

This has some odd and unpredictable effects elsewhere, though, as the `show_controller` is used for other things, and the forward slash has to be assumed to be present, even when this is not desirable. (I encountered these problems on the `NamesController`/`NameDescriptionsController` refactor and decided to try to regularize it upstream.)

Generally I've been switching to symbols everywhere in the app for url builders with a controller/action hash `{ controller: :ctrlr, action: :action }`, and while Rails will accept anything, including an IOU, I'd rather know I'm getting a controller symbol when I call it. 

So here I've i worked out a way to return symbols, eg `:location`, `:observations` for the show_controller, `:show` (or `:show_location`) for the show action, etc, while still fixing the issue of Rails erroneously prepending a controller namespace, closer to the source, in Application Controller. 

The source seems to be Rails `redirect_to`, and this PR prepends the forward slash to the controller name just prior to calling that method. Meanwhile, `Model.show_controller` now always returns the symbol for the controller.

2022-07-24 01:37 UTC, pellaea approved these changes
I think this might be good.  My memory from earlier -- when we had to add the leading slashes because of a rails upgrade or somesuch -- was that this is not terribly well-tested and it should therefore be at least somewhat tested by hand in the dev VM before pushing it out.

2022-08-01 21:09 UTC, JoeCohen requested changes
@nimmolo I finally found the time, and slept enough, to focus on this PR.
I have no substantive suggestions. The comments should be revised to reflect the changes you made to the code.
I can do that if you like; just let me know.

2022-08-03 16:00 UTC, JoeCohen commented on app/models/abstract_model.rb
>    # Note that show_controller has a leading forward slash
Revise documentation (`show_controller` is now a symbol without a leading forward slash)

2022-08-03 17:07 UTC, JoeCohen approved these changes

2022-08-03 17:11 UTC, JoeCohen commented
I:
- pushed my changes to the comments
- pushed the deletion of Observation's now-unnecessary override of `show_controller`.
- merged master into this branch and resolved conflicts.

As @pellaea already approved this branch, I intend to merge it.

2022-08-03 21:20 UTC, nimmolo commented
Sounds good. Thanks, Joe.

> On Aug 3, 2022, at 6:11 PM, Joseph D. Cohen ***@***.***> wrote:
> 
> I:
> 
> pushed my changes to the comments
> pushed the deletion of Observation's now-unnecessary override of show_controller.
> merged master into this branch and resolved conflicts.
> As @pellaea already approved this branch, I intend to merge it.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2022-08-03 22:46 UTC, merged

2022-08-03 23:00 UTC, JoeCohen commented
It's now running on the server

2022-10-11 07:46 UTC, nimmolo commented
Hi Joe, 
Thanks for checking it out. I agree with moving the comments, i'd be glad for you to handle it if you can. 



> On Aug 1, 2022, at 10:10 PM, Joseph D. Cohen ***@***.***> wrote:
> 
> @JoeCohen requested changes on this pull request.
> 
> @nimmolo I finally found the time, and slept enough, to focus on this PR.
> I have no substantive suggestions. The comments should be revised to reflect the changes you made to the code.
> I can do that if you like; just let me know.
> 
> In app/controllers/application_controller.rb:
> 
> > +    # Assure that this method calls a top level controller namespace by putting
> +    # the show_controller in a string after a leading slash.
> Suggestion: Move the comment explaining the / prepend from AbstrctModel to here.
> 
> ⬇️ Suggested change
> -    # Assure that this method calls a top level controller namespace by putting
> -    # the show_controller in a string after a leading slash.
> +    # Assure that this method calls a top level controller namespace by putting
> +    # the show_controller in a string after a leading slash.
> +    # The name must be anchored with a slash to avoid namespacing it.
> +    # references: http://guides.rubyonrails.org/routing.html#controller-namespaces-and-routing
> +    # https://stackoverflow.com/questions/20057910/rails-url-for-behaving-differently-when-using-namespace-based-on-current-cont
> In app/models/abstract_model.rb:
> 
> > @@ -322,6 +322,8 @@ def formatted_errors
>    # that handles the "show_<object>" action for this object.
> The comment should reflect the change from string to symbol.
> (I tried to do this as a GitHub suggestion, but that doesn't work well when commenting on unchanged lines.)
> 
> ⬇️ Suggested change
> -  # that handles the "show_<object>" action for this object.
> +  # Return the name of the controller (as a symbol)
> +  # that handles the "show_<object>" for this object.
> +  # 
> +  #   GlossaryTerm.show_controller 
> +  #     => :glossary_terms (for normalized controller)
> +  # 
> In app/models/abstract_model.rb:
> 
> > @@ -374,9 +376,9 @@ def self.class_defined?(klass)
>    #   Otherwise, perhaps define "index_action" in the individual object class.
>    # JDC 2021-01-14
>    def self.index_action
> Change the preceding comment to reflect change from string to symbol.
> 
> In app/models/abstract_model.rb:
> 
> > @@ -392,9 +394,9 @@ def index_action
>    #   name.show_action => "show_name"
>    #
>    def self.show_action
> Revise preceding documentation to reflect that it's now aymbol
> 
> In app/models/abstract_model.rb:
> 
> > @@ -568,7 +570,9 @@ def destroy_controller
>    #   name.destroy_action => "destroy_name"
>    #
>    def self.destroy_action
> Revise documentation to reflect change from string to symbol
> 
> In app/models/observation.rb:
> 
> > @@ -195,12 +195,7 @@ class Observation < AbstractModel
>  
>    # Override the default show_controller
>    def self.show_controller
> This method also no longer needed.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.