Replace all references to the git branch 'master' with 'main'
MushroomObserver/mushroom-observer pull request #1301
Opened 2023-01-22 23:03 UTC by mo-nathan

2023-01-22 23:39 UTC, JoeCohen requested changes, later dismissed
Thanks for doing this. It looks good and it will nice to get this out of the way.
My only suggestion was using markdown relative links.

2023-01-22 23:39 UTC, JoeCohen commented on README.md
> +[12]: <https://github.com/MushroomObserver/mushroom-observer/blob/main/LICENSE>
Would relative links be better?  See https://github.blog/2013-01-31-relative-links-in-markup-files/
```suggestion
[12]: <LICENSE>
```

2023-01-22 23:39 UTC, JoeCohen commented on README_API.md
> +* <https://github.com/MushroomObserver/mushroom-observer/blob/main/DATA_STRUCTURE.gif>
```suggestion
* [DATA_STRUCTURE.gif](DATA_STRUCTURE.gif)
```

2023-01-22 23:39 UTC, JoeCohen commented on README_API.md
> +* <https://github.com/MushroomObserver/mushroom-observer/blob/main/db/schema.rb>
```suggestion
* [db/schema.rb](db/schema.rb)
```

2023-01-25 22:04 UTC, pellaea commented
Do we need to do that now?  Are now officially on main?

On Wed, Jan 25, 2023 at 4:56 PM andrew nimmo ***@***.***>
wrote:

> Reposting from Nathan's email, so everyone can find it...
> Is this all we need to do, and I'm guessing this will maintain commit
> history?
>
> GitHub says the best way to flip over any local repo is to run:
>
> git branch -m master main
> git fetch origin
> git branch -u origin/main main
> git remote set-head origin -a
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MushroomObserver/mushroom-observer/pull/1301#issuecomment-1404278098>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAYTNNMKETIMIYZDFZP5JMLWUGORFANCNFSM6AAAAAAUDHT65A>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-01-26 01:03 UTC, merged

2023-01-26 01:05 UTC, mo-nathan commented
Had to merge the PR and change the default branch, but now both of those
are done so we should be good to go.

On Wed, Jan 25, 2023 at 5:05 PM Jason Hollinger ***@***.***>
wrote:

> Do we need to do that now? Are now officially on main?
>
> On Wed, Jan 25, 2023 at 4:56 PM andrew nimmo ***@***.***>
> wrote:
>
> > Reposting from Nathan's email, so everyone can find it...
> > Is this all we need to do, and I'm guessing this will maintain commit
> > history?
> >
> > GitHub says the best way to flip over any local repo is to run:
> >
> > git branch -m master main
> > git fetch origin
> > git branch -u origin/main main
> > git remote set-head origin -a
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/MushroomObserver/mushroom-observer/pull/1301#issuecomment-1404278098
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AAYTNNMKETIMIYZDFZP5JMLWUGORFANCNFSM6AAAAAAUDHT65A
> >
> > .
> > You are receiving this because your review was requested.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MushroomObserver/mushroom-observer/pull/1301#issuecomment-1404286707>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAYQDUTZ3T4GJKTF2WOVHRTWUGPRFANCNFSM6AAAAAAUDHT65A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>