Fix Articles destroy links
MushroomObserver/mushroom-observer pull request #657
Opened 2020-09-02 11:00 UTC by JoeCohen

Change `Articles` destroy links to buttons

`destroy` links don't work because they require js,
so use button instead.

- Promote and refactor `destroy_button` method
- Use button instead of link to destroy `article`
- Revise GlossaryTermsHelper and view to work with promoted method

Delivers https://www.pivotaltracker.com/story/show/174524961

Suggested manual test script:
- Go into admin mode
- Create an article. 
  Result: The show_article page should have a "Destroy" link
- Click it.
Result: The article should be destroyed.
- Create a GlossaryTerm
  Result: The show_glossary_term page should have a "Destroy Glossary Term" link
- Click it
  Result: The term should be destroyed.

2020-09-06 21:26 UTC, mo-nathan commented on app/helpers/glossary_terms_helper.rb
> +    destroy_button(object: term, name: :destroy_glossary_term)
Surprisingly not covered by current tests.

2020-09-06 21:27 UTC, mo-nathan requested changes
Functionality and rubocop check out.  Coverage missing for glossary_term_destroy_button.

2020-09-06 22:35 UTC, JoeCohen commented
Thanks for the review. I'll take a look at coverage. I'm also surprised
it's not covered.

On Sun, Sep 6, 2020 at 2:28 PM Nathan Wilson <notifications@github.com>
wrote:

> *@mo-nathan* requested changes on this pull request.
>
> Functionality and rubocop check out. Coverage missing for
> glossary_term_destroy_button.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MushroomObserver/mushroom-observer/pull/657#pullrequestreview-483173867>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAALDFCU3LWGN6LPECI5R2TSEP5GTANCNFSM4QS3YRTQ>
> .
>

2020-09-07 20:51 UTC, mo-nathan approved these changes
Looks good.  Thanks!

2020-09-07 20:51 UTC, merged